### ISSUE TITLE
Please tell me how to upload some CX program/code hello world to Skycoin

### ISSUE THREAD

**Issue by Meai** [skycoin/cx#1]
So I can actually start developing something other than standalone CX programs. The idea here is just like with smartcontracts which you want to make obsolete: I have a program running on the Skycoin network, distributed, and I can talk to it, I am the owner and I am allowed to modify it and other people can talk to it too with their own restrictions and settings that are determined by the program.
Also please explain how CXO fits into CX

**Comment by amherag** [comment]
Hello Meai,

First of all, sorry for the delayed response. I guess the holidays make us all more busy than the usual and I got distracted.

CX's fundamentals are still being developed and tested. For example, at the moment I'm developing support for pointers, and video games are being created using CX to test all of its core features.

We haven't integrated CX with any of the other Skycoin technologies yet, but we want this to happen as soon as possible. We are working hard to make this happen! When the time comes, I'll make sure to upload information on how CX will be integrated with the rest of Skycoin's ecosystem.

Happy holidays!

**Comment by Meai** [comment]
Well it's not so happy for me now because I was banned from the telegram for asking this and I guess being critical about whether it's ready at all.

**Comment by amherag** [comment]
I'm really sorry about that. I'm only in the Game Development channel at the moment, so I'm pretty clueless about your situation. Nevertheless, I asked someone and he believes that you could have been banned because you posted a link and the chat bot banned you.

**Comment by Meai** [comment]
It was only a link to this github issue but okay
