### ISSUE TITLE
Dmsg-http: Request Struct

### ISSUE THREAD

**Issue by Chris-PS** [skycoin/cx#101]
The struct of a dmsg-http request should contain the following information:

- Url
- Options (currently called "method")
- Timestamp (uint64 of time in nano seconds)
- BlockchainHash (latest hash that the request should be ran against)

There is also another, "hidden" parameter called RequestId. The RequestId is the SHA256 hash of the encoder serialized request struct. Therefore it doesn't need to be included in the struct itself. RequestId will be used in the request response. 

The blockchain hash refers to the hash of the CX Chain utilized by the CX application receiving the request.

**Comment by SkycoinSynth** [comment]
Moved to github.com/skycoin/cx-chains
