### ISSUE TITLE
Dmsg-http: Response Struct

### ISSUE THREAD

**Issue by Chris-PS** [skycoin/cx#102]
The response struct should contain the following information:

- NodeId (pub key of the server which executed the request)
- Blockchain (genesis hash that the request was executed against)
- BlockHeight (that the request was executed against)
- HeadBlockHash (the hash of the head block the request was executed against)
- HeadBlockSeq (sequence of the head block)
- HeadBlockTime (uint timestamp of head block)
- RequestId (SHA256 hash of the seralized encoder Request struct)
- ResponseCode (status code, 200, 404, etc.)
- ResponseError (error string - if there is an error, this is filled in, else empty)
- Body/Response (string)

Blockchain related data refers to the CX Chain the CX app is using.

**Comment by SkycoinSynth** [comment]
Moved to github.com/skycoin/cx-chains
