### ISSUE TITLE
Typos in Comments section of Readme.md

### ISSUE THREAD

**Issue by BigOokie** [skycoin/cx#11]
The Comments section of the Readme.md is not well written at the moment and contains unfinished sentences. The below is an extract with `~` added before and after where I see issues

Comments

`~Before continuing with more complex subjects,~`

`~Some of the code snippets that follow have blocks of text that are prefixed by double slashes (//). Double slashes inform the CX parser that what~`

Some of the code snippets that follow have comments in them, i.e., blocks of text that are not actually "run" by the CX compiler or interpreter. Just like in C, Golang and many other programming languages, single line comments are created by placing double slashes (//) before the text being commented. For example:

**Comment by amherag** [comment]
Oops. I was writing some ideas and I forgot to remove them. Thanks, I fixed it now.

**Comment by BigOokie** [comment]
NP 👍
