### ISSUE TITLE
no printf() error when # of directives does not match # of vars

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#112]
example:

printf("\n\n\n%s  %s\n", bar, name, bar)

 "bar" & "name" are string types

**Comment by amherag** [comment]
Golang doesn't throw a runtime error, it just either prints %!s(MISSING), %!d(MISSING), etc (the character after the ! depends on what type it was waiting for to print) or it prints something like %!(EXTRA string=foobar).

Now CX prints a MISSING just like in Golang, and the EXTRA is similar, with the exception that it doesn't print the value. We might print the value later on, but for now I think this is enough.
