### ISSUE TITLE
Continuous integration in Travis for MacOS + Linux

### ISSUE THREAD

**Issue by olemis** [skycoin/cx#12]
Main target : run the tests . @amherag anything else that should be added ?

**Comment by amherag** [comment]
The tests ($ cx tests ) should be enough. I always run other programs to check other features, but the tests should be enough in the near future.

**Comment by olemis** [comment]
@stdevYuniers pls let me know once you join the Skycoin org so as to assign you this issue .

**Comment by stdevYuniers** [comment]
@olemis now you can assign this issue to me

**Comment by stdevYuniers** [comment]
12cc8c0 resolve Travis fails.
On mac it is not necessary install any dev dependency.

Add SonarCloud analysis would be a nice tool for help and localize possible mistakes.

[Travis says that are not any test.](https://travis-ci.org/simelo/cx/jobs/450675547#L144)

Another interesting step would be upload releases artifacts to GitHub when a tag is pushed.
