### ISSUE TITLE
Invalid implicit cast when assigning the result of a math operator to a variable.

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#120]
**Describe the bug**
Invalid implicit cast when assigning the result of a math operator to a variable.

**To Reproduce**
```
package main

func foo()(out i32) {
    out = 4
}

func main()() {
    var a i8 = 1 + 1
    var b i8 = 0-foo()
    var c i8 = -172
}   
```
**Expected behavior**
Compilation error for each line, i8 var can't be initialized with i32 var.

**Desktop (please complete the following information):**
 - OS:linux
 - CX Version v0.7.2 commit : https://github.com/SkycoinProject/cx/commit/93dc014680436c22b2ac576f93f7dcb7e1611324

**Comment by SkycoinSynth** [comment]
Fixed.
