### ISSUE TITLE
Travis/Appveyor needs to run `cx tests/`

### ISSUE THREAD

**Issue by amherag** [skycoin/cx#130]
The source files in `tests` contain all the regression tests for CX.

**Comment by stdevYuniers** [comment]
@amherag Please, can you tell what OS do you use?
Windows builds are Ok, but Linux and Mac are failing.

Have you experienced this error? `./gdk_since_3_22.go.h:22:8: error: unknown type name 'GdkMonitor'`?

**Comment by olemis** [comment]
@yuniers could you please post the URL of the Appveyor build that's failing ?

**Comment by olemis** [comment]
oh ! it's MacOS and GNU/Linux what's failing ... @stdevYuniers pls post the URL pointing at the build failure

**Comment by stdevYuniers** [comment]
> oh ! it's MacOS and GNU/Linux what's failing ... @stdevYuniers pls post the URL pointing at the build failure

[Travis url](https://travis-ci.org/simelo/cx/)
Error is [here](https://travis-ci.org/simelo/cx/jobs/464809382#L2046).

I'm using Debian 9 and with same packages [listed here](https://github.com/simelo/cx/blob/stdevYuniers_t130_ci_appveyor_run_tests/.travis.yml#L18), all installation process was successful.

I will make an Ubuntu Xenial VM to test more deeper.

**Comment by stdevYuniers** [comment]
Windows build are failing due gotk3 error, see gotk3/gotk3#290 and [appveyor job](https://ci.appveyor.com/project/stdevYuniers/cx/builds/20971791#L543).

**Comment by asahi3g** [comment]
I guess tests are failing because they can't locate the cx binary. I'll add a ++cxpath option.
