### ISSUE TITLE
Panic when inserting a new line in a string literal

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#133]
```
package main

func main()() {
    printf("issue
foo")
}
```
Output:
```
"issue
foo"
panic: invalid syntax

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/cxgo0.(*Lexer).Lex(0xc42009ab40, 0xc4201920c0, 0xe010)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.nn.go:7700 +0x21f0
github.com/skycoin/cx/cxgo/cxgo0.yylex1(0x973800, 0xc42009ab40, 0xc4201920c0, 0xc42022e548)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.go:1408 +0x56
github.com/skycoin/cx/cxgo/cxgo0.yyParse(0x973800, 0xc42009ab40, 0xc42009ab40)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.go:1463 +0x2c73
github.com/skycoin/cx/cxgo/cxgo0.Parse(0xc4200c2140, 0x39, 0x38)
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo0/cxgo0.go:74 +0xc8
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8556 +0x367a
```

**Comment by ingwal** [comment]
I'm not sure if newlines are allowed in strings. It works fine if you use 'printf("issue\nfoo")'. I don't see any formal specification of the CX language.

But of course it should give an error message instead of crash.

**Comment by asahi3g** [comment]
Maybe CX should have raw string literals like in golang (delimited by back quotes).

**Comment by ingwal** [comment]
There are two aspects of this:  
 - The allow or disallow of the newline inside a string
 - The panic. 
We should at least fix the panic of the interpreter, but I am inclined to also allow newlines.

**Comment by ingwal** [comment]
> Maybe CX should have raw string literals like in golang (delimited by back quotes).

It does have that.  You can write "string" or `string`.  The second form also allows newlines and other special characters.
