### ISSUE TITLE
Panic if return value is not used.

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#15]
```
var vbo i32
gl.GenBuffers(1, vbo)
```

Panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cx.op_gl_GenBuffers(0xc42049ca00, 0x0)
	/home/oo/go/src/github.com/skycoin/cx/cx/op_opengl.go:78 +0x14d
github.com/skycoin/cx/cx.execNative(0xc420072ea0)
	/home/oo/go/src/github.com/skycoin/cx/cx/opcodes.go:686 +0x12d4
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc4201f6000, 0xc420072ea0, 0x0, 0x0)
	/home/oo/go/src/github.com/skycoin/cx/cx/execute.go:1563 +0x31f
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc420072ea0, 0x0, 0x4, 0xc4201d02c0)
	/home/oo/go/src/github.com/skycoin/cx/cx/execute.go:1487 +0x2ba
main.main()
	/home/oo/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8312 +0x1c5e

No crash with the following code :

```
var vbo i32
vbo = gl.GenBuffers(1, vbo)
```

Maybe it has something to do with pass by ref arguments.
kronos ogls spec for gl.GenBuffers:
```
void glGenBuffers(GLsizei n,  GLuint * buffers);
```

**Comment by amherag** [comment]
Ohhh, well, the behavior is correct. Just like in Golang, if you call a function that's supposed to return something and you do nothing with it, it'll throw an error.

The worrying part in here is that CX should notify you about this.

**Comment by amherag** [comment]
Actually... GenBuffers doesn't return anything in pure OpenGL. I implemented the CX OpenGL this way because we didn't have pointers back then. I don't know if I should change how it's implemented (add pointers) or leave it this way.

**Comment by amherag** [comment]
CX now throws a compile-time error for this:

```
func foo () (name str) {
	name = "Homer"
}

func main () {
	foo()
}
```

If you run the above you'll get something like this error (the error line doesn't match the code above):

```
error: examples/testing.cx:41 operator 'foo' expects to return 1 output, but 0 receiving arguments were provided
```
