### ISSUE TITLE
Issue #133a still persists

### ISSUE THREAD

**Issue by BrandonKoerner** [skycoin/cx#152]
**Describe the bug**
Multiline standard strings are allowed in CX.

**To Reproduce**
see tests/issue-133a.cx

**Expected behavior**
Compilation error.

**Desktop (please complete the following information):**
CX latest version

**Comment by BrandonKoerner** [comment]
They are not allowed, but the previous lexing tool using `nex` still parsed them as complete strings.

new lexing tool can remove this if needed.

**Comment by BrandonKoerner** [comment]
PR #153

**Comment by SkycoinSynth** [comment]
Not sure if multi-line strings are desirable or are language feature.
