### ISSUE TITLE
Error Messages: Bad error messages for missing right parenthesis (or curly brace)

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#161]
Describe the bug

this is a bottom priority thing, and it is fairly obvious what the problem is in my example code.  but when you have a long/complex line/expression, it can take awhile to figure out what the problem is, when the error refers to characters that may not be present in the line/expression. which is what happened to me. :) and CX code is heavy with parentheses pairs with all the longhand expressions currently needed (for reliability).

To Reproduce

use the following code:

"
package main

var sl []i32 = []i32{1,2,3}

func main () {
    printf("len: %d", len(sl)
}
"

i get: "test.cx:6: syntax error: unexpected SEMICOLON".  but there is none

now delete the the right curly brace from line 3, for the same error message (pointing to different line).

now undo (repair line 3 with a closing curly brace).
now reduce line 6 to just "printf(" and you get a DIFFERENT wrong error message:
"test.cx:7: syntax error: unexpected RBRACE"
i've seen error messages that say "PAREN" (or such) before.  in case you might think RBRACE is a catch-all.
also, it points to the wrong line number?  since line 7 is just a closed curly brace.

Expected behavior

it should mention that a matching right parenthesis (or curly brace) is needed.  and report the write line number.

Desktop

OS: Windows 10
CX Version 0.7.0

**Comment by SkycoinSynth** [comment]
@arfan499 Can you add this to regression tests?

**Comment by rizary** [comment]
anyone working on this?

**Comment by SkycoinSynth** [comment]
> anyone working on this?

You can take it if you want.

**Comment by SkycoinSynth** [comment]
No test file.

**Comment by SkycoinSynth** [comment]
Duplicate of #45
