### ISSUE TITLE
can't initialize multidimensional slices with values

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#168]
corpusc opened this issue on Jun 27, 2019
(in the OLD repo, before a move to the newer "SkycoinProject" org lost them)

To Reproduce

Enter this code:
package main

func main() {
    var i [][]i32 = [][]i32{ {1, 2}, {3, 4} }
}

See error:
c.cx:4: syntax error: unexpected LBRACE

Expected behavior
No error

Desktop (please complete the following information):

OS: Windows 10
CX Version 0.7.0 full release

**Comment by SkycoinSynth** [comment]
No support for multi-dimensional arrays.

Note: later improve error message

**Comment by archerixx** [comment]
Only workaround I found for this issue is by adding [2][1]i32 before {1,2} and {3,4}:
```
var i [2][2]i32 = [2][2]i32{ [2][1]i32{1, 2}, [2][1]i32{3, 4}}
```

This issue is mentioned in cx-games under issues: https://github.com/skycoin/cx-games/blob/master/issues/168.cx
