### ISSUE TITLE
Type deduction of struct field fails

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#168]
CX version 0.5.18
```
package main

type test struct {
    sia []i32
    sib []i32
    sic []i32
}

func foo(i i32) {
    test(i, 33, "")
}

func main()() {
    var si []i32
    si = append(si, 33)
    test(si[0], 33, "")

    var t test
    t.sia = si
    test(t.sia[0], 33, "")
}
```
output:
```
byts1 [33 0 0 0 0 0 0 0 0 0 0 0]
byts2 [33 0 0 0]
pending_2.cx: 20: result was not equal to the expected value

```

**Comment by ingwal** [comment]
Should it really be allowed to declare a type with the same name as an already existing function ('test')?

**Comment by olemis** [comment]
As far as I can see from the example , `test` is a struct type , not a function .

**Comment by ingwal** [comment]
Yes, test is a struct type, but a few lines down you call the function test().  This is defined in another file, but the same package.
