### ISSUE TITLE
Compiler Behavior Error: BREAK exits all(?) outer FOR LOOPS

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#174]
corpusc opened this issue on Jul 25, 2019
(in the OLD repo, before a move to the newer "SkycoinProject" org lost them)

To Reproduce

1.  use the following code:

package main

func main() {
for h := 0; h < 5; h++ {
for i := 0; i < 5; i++ {
for j := 0; j < 5; j++ {
break
printf("j: %d \n", j)
}

  str.print("out of j loop")
}

str.print("out of i loop")
}

str.print("out of h loop")
}

2.  notice only the last print "out of h loop" happens
Expected behavior

all 3 "out of _" print statements should be run. j, i then h.

Desktop (please complete the following information):

OS: Windows 10
CX Version: 0.7.0 full release

**Comment by SkycoinSynth** [comment]
@arfan499 Write a unit test with two for loops inside of each other.

Break inside the inner for loop.

And test, should test whether we break from both for loops or only from the inner for loop. With two different outputs depending on the situation.

**Comment by SkycoinSynth** [comment]
Maybe have Break(1), Break(2) for how many levels the break should return from?

**Comment by strayh-username** [comment]
> Maybe have Break(1), Break(2) for how many levels the break should return from?

I think “labeled statements” would be ideal here, if CX doesn’t already support them. Go supports them, but I haven’t coded in Go. Here’s what they look like in Swift:

<img width="1072" alt="Swift-labeled-statements" src="https://user-images.githubusercontent.com/60216685/107045609-fc0f2000-67c5-11eb-9f82-581d759485cb.png">
