### ISSUE TITLE
Compiler  Error Message: Uninformative error msg when importing a package

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#179]
**Bug**
uninformative error msg when importing a package which hasn't been fed to CX.EXE as an argument.

**To Reproduce**

1. The quickest way to verify this would be to go into the "cx-games" repo at
" github.com/skycoin/cx-games/issues/179"
2. Run the program with " cx 179.cx "

**Expected behavior**
For CX to mention that the package file must be included as an argument

**Error message**
" error: 179.cx:2 " (points to the import line)

**Desktop:**
 - OS: Windows 10
 - CX Version 0.7.0

**Comment by SkycoinSynth** [comment]
Compiler error message needs to be updated to be more informative for package imports.
