### ISSUE TITLE
String not working across packages

### ISSUE THREAD

**Issue by redcurse** [skycoin/cx#18]
When trying to access a string variable from a separate package I'm getting unexpected results.

Input
```
package main
import "Test"

func main () {
    str.print(Test.string)
}

package Test
var string str = "test"
```
The output results are blank.

I tested i32, i64, f32, and f64 as well and they all seem to work as expected.

**Comment by amherag** [comment]
The issue is related to inline initializations not being fixed yet. Just as a note. I'm fixing this soon.

For example, if you run the code below, you'll get an output other than blank:

```
package main
import "Test"

func main () {
	Test.test()
	str.print(Test.string)
}

package Test
var string str = "test"

func test () {
	string = "test2"
}

```

**Comment by amherag** [comment]
Solved! You can now inline initialize global variables, even across packages. I feel like we need to test those a bit more though. I tested inline initializing them with expressions and literals, slices too.
