### ISSUE TITLE
Documentation: Delete "Releases" folder and move any information into changelog.md file

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#187]
https://github.com/skycoin/cx/tree/develop/releases
- this folder has change log information

The information in releases must be moved to 
- https://github.com/skycoin/cx/blob/master/CHANGELOG.md

The changelog file needs to be updated for version 7.0 and 7.1
- then the releases folder must be deleted

**Comment by arfan499** [comment]
Done
