### ISSUE TITLE
Makefiles: Move all apt-get install requirements, out of makefile and put them in readme.md in installation instructionss

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#191]
see
- https://github.com/skycoin/cx/issues/69

> echo 'Installing dependencies for Linux'
Installing dependencies for Linux
sudo apt-get update -qq
[sudo] password for d0mo: 
sudo: apt-get: command not found
make: *** [Makefile:54: install-deps-Linux] Error 1

1> Document all apt-get install requirements, in readme.md under installation

2> Remove all apt-get install instructions from make file (as they are operating system specific)

**Comment by some4** [comment]
I'll see if I can create a mux that will run the appropriate OS commands; this way there's less steps for install.

MacOS
Windows10
Linux (Debian, Fedora, Arch, Alpine?)
