### ISSUE TITLE
Unit Tests: Rename Unit Test Numbers

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#192]
Unit tests are located here
- https://github.com/skycoin/cx/tree/develop/tests

Each unit tests is described by an issue number.

The ticket numbers are for ticket tracker in old repo, so the issue numbers for the test do not correspond to current ticket numbers.

- for each unit test named "issue-###", check to see if it corresponds to the correct ticket number here, 
- https://github.com/skycoin/cx/issues
- https://github.com/skycoin/cx/issues/174
-  https://github.com/skycoin/cx/issues/ <--- put issue number here

If the unit test corresponds to the issue number
- put a comment with a link to the issue page at the top of the file
- example: https://github.com/skycoin/cx/issues/174

If the unit test does not correspond to an issue number
- the use link like this https://web.archive.org/web/20200916061849if_/https://github.com/skycoin/cx/issues
- find way back machine link for the issue
- the change the file name from "issue-101.cx" to "_issue-101.cx"

Then
- copy the old ticket from the way back machine link
- such as https://web.archive.org/web/20200916061849if_/https://github.com/skycoin/cx/issues
- to https://github.com/skycoin/cx/issues/
- then rename the issue, with the new ticket number
- then rename the issue to the correct issue number

---

1. Verify that the issue exists for each unit test
2. If the unit test issue number does not exist, then rename unit test file to denote that
3. Find the old ticket on wayback machine and then copy the ticket to new ticket number. Also clean up the ticket text if its bad or not clear or poorly written.
4. Link the unit test to the ticket number with a comment in test file

**Comment by grondonanicolas** [comment]
Tests issues:
- [x] issue-14.cx 
- [x] Issue-15.cx  
- [x] Issue-18.cx
- [x] Issue-19.cx
- [x] Issue-19a.cx
- [x] Issue-23.cx
- [x] Issue-24.cx
- [x] Issue-25.cx 
- [x] Issue-26.cx
- [x] Issue-27.cx
- [x] Issue-28.cx
- [x] Issue-29.cx
- [x] Issue-30.cx
- [x] Issue-32.cx
- [x] Issue-33.cx
- [x] Issue-35.cx
- [x] Issue-37.cx
- [x] Issue-39.cx
- [x] Issue-40.cx
- [x] Issue-41.cx
- [x] Issue-48.cx
- [x] Issue-49.cx
- [x] Issue-50.cx
- [x] Issue-51.cx
- [x] Issue-51a.cx
- [x] Issue-52.cx
- [x] Issue-53.cx
- [x] Issue-54.cx
- [x] Issue-55.cx
- [x] Issue-56.cx
- [x] Issue-57.cx
- [x] Issue-58.cx
- [x] Issue-59a.cx
- [x] Issue-59b.cx
- [x] Issue-60.cx
- [x] Issue-60a.cx
- [x] Issue-61.cx
- [x] Issue-61a.cx
- [x] Issue-62.cx
- [x] Issue-63.cx
- [x] Issue-65.cx
- [x] Issue-65b.cx
- [x] Issue-67.cx
- [x] Issue-68.cx
- [x] Issue-69.cx
- [x] Issue-70.cx
- [x] Issue-71.cx
- [x] Issue-72.cx
- [x] Issue-75.cx
- [x] Issue-76.cx
- [x] Issue-77.cx
- [x] Issue-77b.cx
- [x] Issue-78.cx
- [x] Issue-79.cx
- [x] Issue-82.cx
- [x] Issue-84.cx
- [x] Issue-85.cx
- [x] Issue-86.cx
- [x] Issue-88.cx
- [x] Issue-90.cx
- [x] Issue-91.cx
- [x] Issue-93.cx
- [x] Issue-98.cx
- [x] Issue-99.cx
- [x] Issue-101.cx
- [x] Issue-102.cx
- [x] Issue-103.cx
- [x] Issue-104.cx
- [x] Issue-105.cx
- [x] Issue-106.cx
- [x] Issue-106a.cx
- [x] Issue-108.cx
- [x] Issue-111.cx
- [x] Issue-120-a-SP.cx
- [x] Issue-120-b-SP.cx
- [x] Issue-120-c-SP.cx
- [x] Issue-120.cx
- [x] Issue-120a.cx
- [x] Issue-120b.cx
- [x] Issue-121-SP.cx
- [x] Issue-131-SP.cx
- [x] Issue-132.cx
- [x] Issue-133a.cx
- [x] Issue-133b.cx
- [x] Issue-134.cx
- [x] Issue-135.cx
- [x] Issue-141.cx
- [x] Issue-153.cx
- [x] Issue-154.cx
- [x] Issue-155.cx
- [x] Issue-156.cx
- [x] Issue-157.cx
- [x] Issue-158.cx
- [x] Issue-166.cx
- [x] Issue-167.cx
- [x] Issue-168.cx
- [x] Issue-169.cx
- [x] Issue-170.cx
- [x] Issue-200a.cx
- [x] Issue-200b.cx
- [x] Issue-207a.cx
- [x] Issue-207b.cx
- [x] Issue-214.cx
- [x] Issue-218.cx
- [x] Issue-244.cx
- [x] Issue-247-a.cx
- [x] Issue-247-b.cx
- [x] Issue-264.cx
- [x] Issue-271.cx
- [x] Issue-279.cx
- [x] Issue-280.cx
- [x] Issue-281.cx
- [x] Issue-282.cx
- [x] Issue-283.cx
- [x] Issue-283b.cx
- [x] Issue-284.cx
- [x] Issue-285.cx
- [x] Issue-286.cx
- [x] Issue-287.cx
- [x] Issue-288.cx
- [x] Issue-289.cx
- [x] Issue-290.cx
- [x] Issue-291-a.cx
- [x] Issue-291-b.cx
- [x] Issue-292.cx
- [x] Issue-293.cx
- [x] Issue-294-a.cx
- [x] Issue-294-b.cx
- [x] Issue-338-a.cx
- [x] Issue-338-b.cx
- [x] Issue-338-c.cx
- [x] Issue-358.cx
- [x] Issue-359.cx
- [x] Issue-360.cx
- [x] Issue-361.cx
- [x] Issue-362.cx
- [x] Issue-415.cx
- [x] Issue-481.cx
- [x] Issue-482.cx
- [x] Issue-new-27.cx 
 
Suggested change: 
https://github.com/skycoin/cx/pull/209

New repo issues: 
https://github.com/skycoin/cx/issues/207
https://github.com/skycoin/cx/issues/208

**Comment by skycoin-manager** [comment]
Great Job!
