### ISSUE TITLE
Inconsistent line numbers in test failure messages

### ISSUE THREAD

**Issue by olemis** [skycoin/cx#195]
After editing source code the 

```
go test -race -tags full github.com/skycoin/cx/cxgo/
?   	github.com/skycoin/cx/cxgo	[no test files]
cx ./tests/main.cx ++wdir=./tests ++disable-tests=gui,issue

Running CX tests in dir : './tests'
Enabled tests : 7 : all, issue,
byts1 [2 0 0 0]
byts2 [0 0 0 0]
./tests/main.cx: 104: result was not equal to the expected value; invalid flags
make: *** [test] Error 5
```

Code at line `./tests/main.cx: 104:` is `var TEST_NONE   i32 = 0` . The closest possible failure point seems to be at line `./tests/main.cx: 101:` . It looks like `panic(flags, 0, "invalid flags")`

Chances are that line number tracking needs review .

**Comment by ingwal** [comment]
This seems to be fixed in CX 0.6.2.  Olemis, if you can find a new example, please reopen this bug with a new description.
