### ISSUE TITLE
Compilation error when struct field is named 'input' or 'output'

### ISSUE THREAD

**Issue by asahi3g** [skycoin/cx#286]
**To Reproduce**
```
package main
type too struct {
	input i32
	output i32
}
func main()() {
}

```
**Expected behavior**
Should compile

**Screenshots**
```
tests/pending_7.cx:4: syntax error: unexpected INPUT
```

**Desktop:**
 - OS: Linux
 - CX Version : 0.6.1, https://github.com/skycoin/cx/commit/d8775bfb4500fde31a074507713fc0de47b64e11

**Comment by ingwal** [comment]
I haven't checked, but I am pretty sure that it also doesn't work with other reserved words like 'func', 'for', 'if', etc.  I'm not sure what the reserved keywords 'input' and 'output' are supposed to do, though.
