### ISSUE TITLE
Makefile: does not check for existence of cx executable before running tests

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#315]
Make file does not check for existence of cx executable before running tests

Should use cx executable in cx/bin folder

Not cx executable in path

Should check for existence of cx executable in /bin and report error message if it does not exist

---

~/go/src/github.com/skycoin/cx$ make check-golden-files
GOBIN=/home/cx/go/src/github.com/skycoin/cx/bin go build -tags="base" -i -o /home/cx/go/src/github.com/skycoin/cx/bin/cx github.com/skycoin/cx/cxgo/
chmod +x /home/cx/go/src/github.com/skycoin/cx/bin/cx
ls -1 tests/ | grep '.cx$' | while read -r NAME; do echo "Processing $NAME"; cx -t -co tests/testdata/tokens/${NAME}.txt tests/$NAME || true ; done
Processing issue-120-a.cx
/bin/sh: 1: cx: not found
Processing issue-120-b.cx
/bin/sh: 1: cx: not found
...

**Comment by jdknives** [comment]
This has been fixed. The exact check can be seen here: https://github.com/skycoin/cx/blob/develop/Makefile#L101
