### ISSUE TITLE
Makefile: "make test" does not check whether ./bin/cx executable exists

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#317]
Run
"make build
"rm -rf ./bin"
"make test"

Make test should fail, because the cx executable does not exist.

1> The tests run without confirming the existence of the CX executable

2> The error message is "os.RUN_START_FAILED (3) | i32"
- but error message should be "/bin/sh: 1: cx: not found"
- should indicate that cx executable does not exist instead of useless error messages
- tests should abort with message, if cx executable does not exist in cx/bin

3> Also https://github.com/skycoin/cx/issues/316
- make test, should use /bin/cx instead of cx on path

---

cx@cx:~/go/src/github.com/skycoin/cx$ rm -rf ./bin
cx@cx:~/go/src/github.com/skycoin/cx$ make test
GOBIN=/home/cx/go/src/github.com/skycoin/cx/bin go build -tags="base" -i -o /home/cx/go/src/github.com/skycoin/cx/bin/cx github.com/skycoin/cx/cxgo/
chmod +x /home/cx/go/src/github.com/skycoin/cx/bin/cx
GOBIN=/home/cx/go/src/github.com/skycoin/cx/bin go test -race -tags base github.com/skycoin/cx/cxgo/
?   	github.com/skycoin/cx/cxgo	[no test files]
/home/cx/go/src/github.com/skycoin/cx/bin/cx ./lib/args.cx ./tests/main.cx ++wdir=./tests ++disable-tests=gui,issue
Stating file : '', '/home/cx/cx/'
Stating file : '', '/home/cx/cx/bin'
Stating file : '', '/home/cx/cx/pkg'
Stating file : '', '/home/cx/cx/src'
Stating file : '', './lib/args.cx'
CXOpenFile: Opening 'lib/args.cx'
Stating file : '', './tests/main.cx'
CXOpenFile: Opening 'tests/main.cx'

Running CX tests in dir : './tests'
Enabled tests : 1 : [ stable,  ]
Enabled log : 4 : [ fail,  ]

#  0 | FAILED  | na | 'cx test-i8.cx' | os.Run exited with code os.RUN_START_FAILED (3) | i32
#  1 | FAILED  | na | 'cx test-i16.cx' | os.Run exited with code os.RUN_START_FAILED (3) | i32
#  2 | FAILED  | na | 'cx test-i32.cx' | os.Run exited with code os.RUN_START_FAILED (3) | i32
#  3 | FAILED  | na | 'cx test-i64.cx' | os.Run exited with code os.RUN_START_FAILED (3) | i64
#  4 | FAILED  | na | 'cx test-ui8.cx' | os.Run exited with code os.RUN_START_FAILED (3) | i32
#  5 | FAILED  | na | 'cx test-ui16.cx' | os.Run exited with code os.RUN_START_FAILED (3) | i32
#  6 | FAILED  | na | 'cx test-ui32.cx' | os.Run exited with code os.RUN_START_FAILED (3) | i32
#  7 | FAILED  | na | 'cx test-ui64.cx' | os.Run exited with code os.RUN_START_FAILED (3) | i64

**Comment by rizary** [comment]
It is strange that you have `GOBIN=/home/cx/go/src/github.com/skycoin/cx/bin go build -tags="base" -i -o /home/cx/go/src/github.com/skycoin/cx/bin/cx github.com/skycoin/cx/cxgo/` in your environment variable. How did you get your `$GOBIN` path in the first place?
