### ISSUE TITLE
Cannot start game.cx

### ISSUE THREAD

**Issue by archerixx** [skycoin/cx#328]
**Describe the bug**
After installing cx and following guide on https://github.com/skycoin/cx README.md. Under part "Run CX program" Hello World program works fine, but when running 'cx examples/opengl/game.cx' there is issue.

**To Reproduce**
1. Install CX from https://github.com/skycoin/cx
2. Run 'cx examples/opengl/game.cx'

Expected output:

```
Stating file : '', 'game.cx'
CXOpenFile: Opening 'game.cx'
panic: struct 'CreateShader' not found in package 'gl'

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.PostfixExpressionField(0xc00008e828, 0x1, 0x1, 0xc00028ca60, 0xc, 0xc00028ca20, 0x0, 0x1)
        C:/Users/tursi/go/src/github.com/skycoin/CX/cxgo/actions/postfix.go:313 +0x1df4
github.com/skycoin/cx/cxgo/parser.yyParse(0xa86480, 0xc0001ac5a0, 0xc0001ac5a0)
        C:/Users/tursi/go/src/github.com/skycoin/CX/cxgo/parser/cxgo.go:2234 +0x7217
github.com/skycoin/cx/cxgo/parser.Parse(...)
        C:/Users/tursi/go/src/github.com/skycoin/CX/cxgo/parser/cxgo.go:18
github.com/skycoin/cx/cxgo/cxgo.ParseSourceCode(0xc00008e040, 0x1, 0x1, 0xc00008c430, 0x1, 0x1)
        C:/Users/tursi/go/src/github.com/skycoin/CX/cxgo/cxgo/cxgo.go:78 +0x40b
main.parseProgram(0x0, 0x992a98, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/tursi/go/src/github.com/skycoin/CX/cxgo/main.go:486 +0x512
main.Run(0xc0000044b0, 0x1, 0x1)
        C:/Users/tursi/go/src/github.com/skycoin/CX/cxgo/main.go:773 +0x3ba
main.main()
        C:/Users/tursi/go/src/github.com/skycoin/CX/cxgo/main_desktop.go:14 +0x72
```

**Expected behavior**
Should run cx game

**Screenshots**
![image](https://user-images.githubusercontent.com/17955370/108610779-abf4a800-73d8-11eb-8499-2aef475ce6f0.png)

**Desktop:**
 - OS: Windows 10
 - CX Version 0.7.1

**Additional context**
This seems to be caused by gl, gltext, glfw that have issue being installed upon initial cx-setup.bat. Program Hello World seems to be working fine, which means cx is installed, but games wont launch. gl and gltext can be installed after managing GOPATH Environment to mach with cx Environment, but glfw is still missing. Because of following error:

```
Issuing command: 'go get github.com\go-gl\glfw\v3.2\glfw'
go: found github.com/go-gl/glfw/v3.2/glfw in github.com/go-gl/glfw v0.0.0-20201108214237-06ea97f0c265
# github.com/go-gl/glfw/v3.2/glfw
cgo: exec /missing-cc: exec: "/missing-cc": file does not exist
ERROR GETting go-gl\glfw\v3.2\glfw
********* ERROR CODE: 2 *********
```

**Comment by marti1125** [comment]
you can try to install http://mingw-w64.org/doku.php/download/mingw-builds

**Comment by archerixx** [comment]
After installing -gcc and setting it up on Windows, Gl/Glfw packages work fine in GoLang. Which proves that C compiler and OpenGL work fine.
Unfortunately, same issue is still happening when running any .cx from cx/examples/opengl.
It stops at first Struct from `gl` or `glfw` and bring up error mentioned in this issue.

I have tested `gl` and `glfw` in GoLang and run simple example of Cube from `https://github.com/go-gl/example/tree/master/gl21-cube`

Either Windows cant communicate well with Imported packages or gl/glfw's Structures are causing some issues here
