### ISSUE TITLE
Include C compiler and git setup instructions in Readme

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#329]
Readme.md must include instructions for 
- installing git

And we must determine if it is required that a user have a C compiler installed.
- and if so , then we must have instructions for installing the C compiler

**Comment by archerixx** [comment]
Instruciton added for Installing GIT. Still testing if C compiler is needed.

**Comment by marti1125** [comment]
try to install http://mingw-w64.org/doku.php/download/mingw-builds for get gcc

**Comment by archerixx** [comment]
GCC compiler needed for gl/glfw to be installed. Best option would be to add additional command in README.md where 'pacman' commands are. I will edit readme.md and offer changes.  MSYS2 program is needed for pacman commands on Windows, so I belive that should be downloaded beside GIT.

**Comment by archerixx** [comment]
Instructions for installing GIT and C compiler added in README. This can be closed now i belive
