### ISSUE TITLE
Include gl glfw install instructions in Readme

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#330]
Windows installation do not include gl/glfw dependencies.

Why are dependency installation instructions missing for windows?

---

Windows users must have installed GIT.
- instructions for installing git on windows must be given

---

Dependencies may be listed in cx-setup.bat file

**Comment by archerixx** [comment]
cx-setup.bat includes gl/glfw dependencies, but only one version. Some of GO files require other glfw version which are not installed with batch file.
Gl/glfw can be only set if -gcc %PATH% exists on Windows machines.

**Comment by archerixx** [comment]
`cx-setup.bat` contains gl/glfw dependencies for versions `go-gl\gl\v2.1\gl` and `go-gl\glfw\v3.2\glfw` respectively.
Although, some GO files require other versions, i.e `%gopath%\src\github.com\skycoin\CX\cxfx\cxgl_desktop` which are newer then one being called in `cx-setup.bat`. Not sure if this might cause some issues. If not, then this issue can be closed.

![Gl_Glfw version](https://user-images.githubusercontent.com/17955370/109551586-0674bf00-7ad1-11eb-99fb-8cd244a5ce3c.PNG)
