### ISSUE TITLE
Issue with Tests when compiling main.cx from https://github.com/skycoin/cx/tree/develop/tests

### ISSUE THREAD

**Issue by archerixx** [skycoin/cx#336]
Describe the bug
Running 'cx main.cx in https://github.com/skycoin/cx/tree/develop/tests' produces error message after cx-setup.bat or after manually running 'cx main.cx' or 'cx test-args.cx'.

To Reproduce
Go to Command Prompt after installing CX on Windows machines.
Run command: 'cx main.cx' while in tests directory
Check 5th line after running above command
See error:
Stating file : '', 'C:\Users\tursi\cx\src\github.com\skycoin\CX\src\args'
Failed to stat file : '', 'C:\Users\tursi\cx\src\github.com\skycoin\CX\src\args', err 'CreateFile C:\Users\tursi\cx\src\github.com\skycoin\CX\src\args: The system cannot find the file specified.'
C:\Users\tursi\cx\src\github.com\skycoin\CX\src\args: source file or library not found

Expected behavior
Should finish tests and confirm CX installation

Screenshots
![image](https://user-images.githubusercontent.com/17955370/108626585-24974b00-7451-11eb-9edd-68eb6ededb32.png)

Desktop:
OS: Windows 10
CX Version 0.7.1

**Comment by SkycoinSynth** [comment]
Have you run "cx" on command line and see if command works?

**Comment by archerixx** [comment]
> Have you run "cx" on command line and see if command works?

It works only on simple tasks like "Hello-World.cx", "Factorial.cx", "even-or-odd.cx.
When i go to openGL, none of examples that I run so far worked, because of glfw

**Comment by archerixx** [comment]
This was related to issue https://github.com/skycoin/cx/issues/394 which is resolved
