### ISSUE TITLE
README: Compiling from Source 

### ISSUE THREAD

**Issue by ivankonevv** [skycoin/cx#343]
When installing via compilation from source, when executing the command:
`go get github.com/skycoin/cx@develop`
an error is thrown:
`go: cannot use path@version syntax in GOPATH mode`
Solved by entering the command:
`export GO111MODULE=on`
Correction suggestion:
  Add this line to readme.md: `export GO111MODULE=on`

Desktop:
OS: macOS BigSur 11.0.1
CX Version 0.7.1 
GoLang version 1.15.7

**Comment by SkycoinSynth** [comment]
Fixed.
