### ISSUE TITLE
Error make install latest cx

### ISSUE THREAD

**Issue by pitulloz** [skycoin/cx#352]
command:
go get github.com/skycoin/cx/cx/...
make install
...
...

```
go build -tags full -i -o /home/yanito/go/bin/cx github.com/skycoin/cx/cxgo/
# github.com/skycoin/cx/cxgo
cxgo/main.go:30:2: FIELD redeclared during import "github.com/skycoin/cx/cxgo/parser"
	previous declaration at cxgo/cxgo.go:105:20
cxgo/main.go:30:2: PACKAGE redeclared during import "github.com/skycoin/cx/cxgo/parser"
	previous declaration at cxgo/cxgo.go:158:20
cxgo/main.go:30:2: LTHANWORD redeclared during import "github.com/skycoin/cx/cxgo/parser"
	previous declaration at cxgo/cxgo.go:137:20
cxgo/main.go:30:2: PLUSPLUS redeclared during import "github.com/skycoin/cx/cxgo/parser"
	previous declaration at cxgo/cxgo.go:161:20
cxgo/main.go:30:2: TYPE redeclared during import "github.com/skycoin/cx/cxgo/parser"
	previous declaration at cxgo/cxgo.go:189:20
cxgo/main.go:30:2: AFFVAR redeclared during import "github.com/skycoin/cx/cxgo/parser"
	previous declaration at cxgo/cxgo.go:59:20
cxgo/main.go:30:2: FUNC redeclared during import "github.com/skycoin/cx/cxgo/parser"
	previous declaration at cxgo/cxgo.go:108:20
cxgo/main.go:30:2: RIGHTSHIFTEQ redeclared during import "github.com/skycoin/cx/cxgo/parser"
	previous declaration at cxgo/cxgo.go:172:20
cxgo/main.go:30:2: INC_OP redeclared during import "github.com/skycoin/cx/cxgo/parser"
	previous declaration at cxgo/cxgo.go:122:20
cxgo/main.go:30:2: REM redeclared during import "github.com/skycoin/cx/cxgo/parser"
	previous declaration at cxgo/cxgo.go:167:20
cxgo/main.go:30:2: too many errors
Makefile:49: recipe for target 'build' failed
make: *** [build] Error 2

```

**Comment by BigOokie** [comment]
@pitulloz what OS are you using?

I am using MacOS Mojave (10.14.4) and also have issues with `make install` for `CX` for both `master` and `develop` branches, but confirm that it works for the `release-0.6` branch (which was the last official binary release).

**Comment by pitulloz** [comment]
@BigOokie I am using Ubuntu 18.04.2 LTS 64 Bit OS, bug error make cx develop branch 4ba0d2... right now I am using cx version 0.6.2 from binary release, so no blockchain feature yet.

**Comment by BigOokie** [comment]
@pitulloz what version of `Go` do you have installed? Your error messages are slightly different to mine. And Mine are slightly different for each of the versions of `Go` I tried.

**Comment by pitulloz** [comment]
@BigOokie go1.11.4

**Comment by BigOokie** [comment]
So it looks like something was junked up on my system. Not entirely sure what was going on and causing it 🤔...
I ended up deleted my local copy of the repo and re-cloned it and now its working. 
The `develop` branch is building with `Go 1.10.8`, `Go 1.11.6`, and `Go 1.12.4`

Very weird. So ignore the info I provided above - it doesn't seem to be an issue (for me).

**Comment by pitulloz** [comment]
delete cx and re-clone fix problem. thanks.

**Comment by BigOokie** [comment]
@pitulloz so it worked for you also?  
nice. 👍
