### ISSUE TITLE
Readme: Add goproxy options for Chinese developers

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#361]
We need to add at least two different options for goproxy settings, for developers in China to user

Make build/make clean/make install CANNOT use internet. All dependencies must be internal to repo to pulled in another step, because of goproxy settings and china internet blocking issue.

---

export GOPROXY=https://goproxy.cn

export GOPROXY=https://goproxy.io

**Comment by jdknives** [comment]
@SkycoinSynth I will close this ticket. The Makefile does not use commands that require network access anymore. Chinese developers should be able to use the Makefile without any issue. This is a general development setup step for Go devs in China. If you still want us to add this to the setup documentation, we can reopen the ticket.
