### ISSUE TITLE
cx ./tests failed after installed

### ISSUE THREAD

**Issue by etmad8** [skycoin/cx#367]
[root@zabbix-dmz cx]# make install
Installing go package dependencies
GOBIN=/root/go/bin go get -u modernc.org/goyacc
GOBIN=/root/go/bin go build -tags="base" -i -o /root/go/bin/cx github.com/skycoin/cx/cxgo/
go build: -i flag is deprecated
chmod +x /root/go/bin/cx
mkdir -p /root/cx/src /root/cx/bin /root/cx/pkg
NOTE:\tCX workspace at /root/cx
NOTE:\tWe recommend you to test your CX installation by running "cx ./tests"
/root/go/bin/cx -v
Stating file : '', '/root/cx/'
Stating file : '', '/root/cx/bin'
Stating file : '', '/root/cx/pkg'
Stating file : '', '/root/cx/src'
CX version 0.7.1
[root@zabbix-dmz cx]# cx ./tests
Stating file : '', '/root/cx/'
Stating file : '', '/root/cx/bin'
Stating file : '', '/root/cx/pkg'
Stating file : '', '/root/cx/src'
Stating file : '', './tests'
CXOpenFile: Opening 'tests/Makefile'
CXOpenFile: Opening 'tests/issue-1.cx'
CXOpenFile: Opening 'tests/issue-120-a.cx'
CXOpenFile: Opening 'tests/issue-120-b.cx'
CXOpenFile: Opening 'tests/issue-120-c.cx'
CXOpenFile: Opening 'tests/issue-121.cx'
CXOpenFile: Opening 'tests/issue-131.cx'
CXOpenFile: Opening 'tests/issue-157.cx'
CXOpenFile: Opening 'tests/issue-177/structofslicechar.cx'
CXOpenFile: Opening 'tests/issue-177/structofsliceint32.cx'
CXOpenFile: Opening 'tests/issue-177/structofslicestring.cx'
CXOpenFile: Opening 'tests/issue-177/structofslicestrings.cx'
CXOpenFile: Opening 'tests/issue-2.cx'
CXOpenFile: Opening 'tests/issue-200a.cx'
CXOpenFile: Opening 'tests/issue-200b.cx'
CXOpenFile: Opening 'tests/issue-207.cx'
CXOpenFile: Opening 'tests/issue-208.cx'
CXOpenFile: Opening 'tests/issue-214.cx'
CXOpenFile: Opening 'tests/issue-215.cx'
CXOpenFile: Opening 'tests/issue-215a.cx'
CXOpenFile: Opening 'tests/issue-216.cx'
CXOpenFile: Opening 'tests/issue-217.cx'
CXOpenFile: Opening 'tests/issue-218.cx'
CXOpenFile: Opening 'tests/issue-219.cx'
CXOpenFile: Opening 'tests/issue-220.cx'
CXOpenFile: Opening 'tests/issue-221.cx'
CXOpenFile: Opening 'tests/issue-222.cx'
CXOpenFile: Opening 'tests/issue-223.cx'
CXOpenFile: Opening 'tests/issue-224.cx'
CXOpenFile: Opening 'tests/issue-225.cx'
CXOpenFile: Opening 'tests/issue-226.cx'
CXOpenFile: Opening 'tests/issue-227.cx'
CXOpenFile: Opening 'tests/issue-230.cx'
CXOpenFile: Opening 'tests/issue-231.cx'
CXOpenFile: Opening 'tests/issue-232.cx'
CXOpenFile: Opening 'tests/issue-233.cx'
CXOpenFile: Opening 'tests/issue-234.cx'
CXOpenFile: Opening 'tests/issue-235.cx'
CXOpenFile: Opening 'tests/issue-236.cx'
CXOpenFile: Opening 'tests/issue-236a.cx'
CXOpenFile: Opening 'tests/issue-237.cx'
CXOpenFile: Opening 'tests/issue-238.cx'
CXOpenFile: Opening 'tests/issue-239.cx'
CXOpenFile: Opening 'tests/issue-240.cx'
CXOpenFile: Opening 'tests/issue-241.cx'
CXOpenFile: Opening 'tests/issue-242.cx'
CXOpenFile: Opening 'tests/issue-243.cx'
CXOpenFile: Opening 'tests/issue-244a.cx'
CXOpenFile: Opening 'tests/issue-244b.cx'
CXOpenFile: Opening 'tests/issue-245.cx'
CXOpenFile: Opening 'tests/issue-245a.cx'
CXOpenFile: Opening 'tests/issue-246.cx'
CXOpenFile: Opening 'tests/issue-246a.cx'
CXOpenFile: Opening 'tests/issue-247.cx'
CXOpenFile: Opening 'tests/issue-248.cx'
CXOpenFile: Opening 'tests/issue-249.cx'
CXOpenFile: Opening 'tests/issue-249b.cx'
CXOpenFile: Opening 'tests/issue-250.cx'
CXOpenFile: Opening 'tests/issue-251.cx'
CXOpenFile: Opening 'tests/issue-252.cx'
CXOpenFile: Opening 'tests/issue-253.cx'
CXOpenFile: Opening 'tests/issue-254.cx'
CXOpenFile: Opening 'tests/issue-255.cx'
CXOpenFile: Opening 'tests/issue-256.cx'
CXOpenFile: Opening 'tests/issue-257.cx'
CXOpenFile: Opening 'tests/issue-258.cx'
CXOpenFile: Opening 'tests/issue-258b.cx'
CXOpenFile: Opening 'tests/issue-259.cx'
CXOpenFile: Opening 'tests/issue-260.cx'
CXOpenFile: Opening 'tests/issue-261.cx'
CXOpenFile: Opening 'tests/issue-262.cx'
CXOpenFile: Opening 'tests/issue-263.cx'
CXOpenFile: Opening 'tests/issue-264.cx'
CXOpenFile: Opening 'tests/issue-265.cx'
CXOpenFile: Opening 'tests/issue-266.cx'
CXOpenFile: Opening 'tests/issue-267.cx'
CXOpenFile: Opening 'tests/issue-268.cx'
CXOpenFile: Opening 'tests/issue-269.cx'
CXOpenFile: Opening 'tests/issue-27.cx'
CXOpenFile: Opening 'tests/issue-270.cx'
CXOpenFile: Opening 'tests/issue-271.cx'
CXOpenFile: Opening 'tests/issue-272.cx'
CXOpenFile: Opening 'tests/issue-273.cx'
CXOpenFile: Opening 'tests/issue-274.cx'
CXOpenFile: Opening 'tests/issue-275.cx'
CXOpenFile: Opening 'tests/issue-276.cx'
CXOpenFile: Opening 'tests/issue-276a.cx'
CXOpenFile: Opening 'tests/issue-277.cx'
CXOpenFile: Opening 'tests/issue-278.cx'
CXOpenFile: Opening 'tests/issue-279.cx'
CXOpenFile: Opening 'tests/issue-279a.cx'
CXOpenFile: Opening 'tests/issue-279b.cx'
CXOpenFile: Opening 'tests/issue-280.cx'
CXOpenFile: Opening 'tests/issue-281.cx'
CXOpenFile: Opening 'tests/issue-282a.cx'
CXOpenFile: Opening 'tests/issue-282b.cx'
CXOpenFile: Opening 'tests/issue-283.cx'
CXOpenFile: Opening 'tests/issue-284.cx'
CXOpenFile: Opening 'tests/issue-285.cx'
CXOpenFile: Opening 'tests/issue-286.cx'
CXOpenFile: Opening 'tests/issue-287.cx'
CXOpenFile: Opening 'tests/issue-288.cx'
CXOpenFile: Opening 'tests/issue-289.cx'
CXOpenFile: Opening 'tests/issue-28a-f32-decrement.cx'
CXOpenFile: Opening 'tests/issue-28a-f32-increment.cx'
CXOpenFile: Opening 'tests/issue-28a-f64-decrement.cx'
CXOpenFile: Opening 'tests/issue-28a-f64-increment.cx'
CXOpenFile: Opening 'tests/issue-28a-i16-decrement.cx'
CXOpenFile: Opening 'tests/issue-28a-i16-increment.cx'
CXOpenFile: Opening 'tests/issue-28a-i32-decrement.cx'
CXOpenFile: Opening 'tests/issue-28a-i32-increment.cx'
CXOpenFile: Opening 'tests/issue-28a-i64-decrement.cx'
CXOpenFile: Opening 'tests/issue-28a-i64-increment.cx'
CXOpenFile: Opening 'tests/issue-28a-i8-decrement.cx'
CXOpenFile: Opening 'tests/issue-28a-i8-increment.cx'
CXOpenFile: Opening 'tests/issue-28a-ui16-decrement.cx'
CXOpenFile: Opening 'tests/issue-28a-ui16-increment.cx'
CXOpenFile: Opening 'tests/issue-28a-ui32-decrement.cx'
CXOpenFile: Opening 'tests/issue-28a-ui32-increment.cx'
CXOpenFile: Opening 'tests/issue-28a-ui64-decrement.cx'
CXOpenFile: Opening 'tests/issue-28a-ui64-increment.cx'
CXOpenFile: Opening 'tests/issue-28a-ui8-increment.cx'
CXOpenFile: Opening 'tests/issue-28b-f32-postfix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-f32-prefix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-f64-postfix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-f64-prefix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-i16-postfix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-i16-prefix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-i32-postfix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-i32-prefix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-i64-postfix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-i64-prefix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-i8-postfix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-i8-prefix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-ui16-postfix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-ui16-prefix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-ui32-postfix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-ui32-prefix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-ui64-postfix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-ui64-prefix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-ui8-postfix_increment.cx'
CXOpenFile: Opening 'tests/issue-28b-ui8-prefix_increment.cx'
CXOpenFile: Opening 'tests/issue-290.cx'
CXOpenFile: Opening 'tests/issue-291.cx'
CXOpenFile: Opening 'tests/issue-292.cx'
CXOpenFile: Opening 'tests/issue-293.cx'
CXOpenFile: Opening 'tests/issue-294.cx'
CXOpenFile: Opening 'tests/issue-295.cx'
CXOpenFile: Opening 'tests/issue-296.cx'
CXOpenFile: Opening 'tests/issue-297a.cx'
CXOpenFile: Opening 'tests/issue-297b.cx'
CXOpenFile: Opening 'tests/issue-298.cx'
CXOpenFile: Opening 'tests/issue-299.cx'
CXOpenFile: Opening 'tests/issue-300.cx'
CXOpenFile: Opening 'tests/issue-301-a.cx'
CXOpenFile: Opening 'tests/issue-301-b.cx'
CXOpenFile: Opening 'tests/issue-302.cx'
CXOpenFile: Opening 'tests/issue-303.cx'
CXOpenFile: Opening 'tests/issue-304.cx'
CXOpenFile: Opening 'tests/issue-305.cx'
CXOpenFile: Opening 'tests/issue-306.cx'
CXOpenFile: Opening 'tests/issue-308.cx'
CXOpenFile: Opening 'tests/issue-309.cx'
CXOpenFile: Opening 'tests/issue-310.cx'
CXOpenFile: Opening 'tests/issue-311.cx'
CXOpenFile: Opening 'tests/issue-39.cx'
CXOpenFile: Opening 'tests/issue-48.cx'
CXOpenFile: Opening 'tests/issue-49.cx'
CXOpenFile: Opening 'tests/issue-50.cx'
CXOpenFile: Opening 'tests/issue-51.cx'
CXOpenFile: Opening 'tests/issue-53-a.cx'
CXOpenFile: Opening 'tests/issue-53-b.cx'
CXOpenFile: Opening 'tests/issue-53-c.cx'
CXOpenFile: Opening 'tests/issue-59-a.cx'
CXOpenFile: Opening 'tests/issue-59-b.cx'
CXOpenFile: Opening 'tests/issue-60.cx'
CXOpenFile: Opening 'tests/issue-61-a.cx'
CXOpenFile: Opening 'tests/issue-61-b.cx'
CXOpenFile: Opening 'tests/issue-62.cx'
CXOpenFile: Opening 'tests/issue-63.cx'
CXOpenFile: Opening 'tests/issue-64.cx'
CXOpenFile: Opening 'tests/issue-64b.cx'
CXOpenFile: Opening 'tests/issue-65.cx'
CXOpenFile: Opening 'tests/issue-66.cx'
CXOpenFile: Opening 'tests/issue-67.cx'
CXOpenFile: Opening 'tests/issue-68.cx'
CXOpenFile: Opening 'tests/main.cx'
CXOpenFile: Opening 'tests/test-ar-1.cx'
CXOpenFile: Opening 'tests/test-args.cx'
CXOpenFile: Opening 'tests/test-array.cx'
CXOpenFile: Opening 'tests/test-bool.cx'
CXOpenFile: Opening 'tests/test-cipher.cx'
CXOpenFile: Opening 'tests/test-collection-functions.cx'
CXOpenFile: Opening 'tests/test-control-flow.cx'
CXOpenFile: Opening 'tests/test-f32.cx'
CXOpenFile: Opening 'tests/test-f64.cx'
CXOpenFile: Opening 'tests/test-function.cx'
CXOpenFile: Opening 'tests/test-gc.cx'
CXOpenFile: Opening 'tests/test-i16.cx'
CXOpenFile: Opening 'tests/test-i32.cx'
CXOpenFile: Opening 'tests/test-i64.cx'
CXOpenFile: Opening 'tests/test-i8.cx'
CXOpenFile: Opening 'tests/test-json.cx'
CXOpenFile: Opening 'tests/test-parse.cx'
CXOpenFile: Opening 'tests/test-pointers.cx'
CXOpenFile: Opening 'tests/test-regexp-compile-fail.cx'
CXOpenFile: Opening 'tests/test-regexp-must-compile-fail.cx'
CXOpenFile: Opening 'tests/test-regexp.cx'
CXOpenFile: Opening 'tests/test-scopes.cx'
CXOpenFile: Opening 'tests/test-short-declarations.cx'
CXOpenFile: Opening 'tests/test-slices-index-out-of-range-a.cx'
CXOpenFile: Opening 'tests/test-slices-index-out-of-range-b.cx'
CXOpenFile: Opening 'tests/test-slices-insert-out-of-range-a.cx'
CXOpenFile: Opening 'tests/test-slices-insert-out-of-range-b.cx'
CXOpenFile: Opening 'tests/test-slices-remove-out-of-range-a.cx'
CXOpenFile: Opening 'tests/test-slices-remove-out-of-range-b.cx'
CXOpenFile: Opening 'tests/test-slices-remove-out-of-range-c.cx'
CXOpenFile: Opening 'tests/test-slices-resize-out-of-range-a.cx'
CXOpenFile: Opening 'tests/test-slices-resize-out-of-range-b.cx'
CXOpenFile: Opening 'tests/test-slices.cx'
CXOpenFile: Opening 'tests/test-str.cx'
CXOpenFile: Opening 'tests/test-struct.cx'
CXOpenFile: Opening 'tests/test-ui16.cx'
CXOpenFile: Opening 'tests/test-ui32.cx'
CXOpenFile: Opening 'tests/test-ui64.cx'
CXOpenFile: Opening 'tests/test-ui8.cx'
CXOpenFile: Opening 'tests/test-utils.cx'
CXOpenFile: Opening 'tests/test-workspace/src/math/arithmetic.cx'
CXOpenFile: Opening 'tests/test-workspace/src/math/geometry/shapes-methods.cx'
CXOpenFile: Opening 'tests/test-workspace/src/math/geometry/shapes.cx'
CXOpenFile: Opening 'tests/test-workspace-a.cx'
CXOpenFile: Opening 'tests/test-workspace-b.cx'
CXOpenFile: Opening 'tests/test-workspace-c.cx'
CXOpenFile: Opening 'tests/test-workspace-d.cx'
CXOpenFile: Opening 'tests/testdata/json/test-0.json'
Stating file : '', '/root/cx/src/args'
Failed to stat file : '', '/root/cx/src/args', err 'stat /root/cx/src/args: no such file or directory'
/root/cx/src/args: source file or library not found

**Comment by SkycoinSynth** [comment]
Unknown
