### ISSUE TITLE
"cx yacc" sub-command

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#368]
Make a CLI option for "cx yacc" to eliminate the YACC executable. And have only a single executable.

modernc.org/goyacc
- wrap this library

In build file it is 

```
install-deps:
	@echo "Installing go package dependencies"
	$(GO_OPTS) go get -u modernc.org/goyacc
```

**Comment by SkycoinSynth** [comment]
cx/yacc now works

**Comment by amherag** [comment]
We don't need this (Synth and I agreed on this in a meeting).
