### ISSUE TITLE
CX chains errors with big programs

### ISSUE THREAD

**Issue by amherag** [skycoin/cx#389]
**Describe the bug**
A CX chain will fail to broadcast a transaction if the program state is of a relatively large size. The error is triggered at different sizes, but the value is in a range of 15 Kb to 100 Kb. The error that is thrown by CX is the following:

```
400 Bad Request - no unspents to spend
```

A log from the peer node is attached in the Screenshots section, with the error highlighted.

**To Reproduce**
1. Have a working CX 0.7beta installation.
2. Set the following environment variables (in a Linux system) or just take note of them and replace them manually where appropriate:

```
export GENESIS_ADDRESS=23v7mT1uLpViNKZHh9aww4VChxizqKsNq4E
export SECRET_KEY=1414535274594b23ca0090cdc01e6b7b31702525583eb01c8650a650d4a8c99d
export PUBLIC_KEY=02583e5ebbf85522474e0f17e681e62ca37910db6b8792763af4e97663c31a7984
```

3. Save the following code in a file named `matrix-bc.cx`:

```
package bc

var matrix [500][500]i32

package main

func main() {
}
```

4. Save the following code in a file named `matrix-txn.cx`:

```
package main
import "bc"

func main() {
}
```

5. Initialize the CX chain:

```
cx --secret-key $SECRET_KEY --public-key $PUBLIC_KEY --blockchain matrix-bc.cx
```

6. Using the genesis signature printed to standard output, set a `GENESIS_SIGNATURE` variable. For example:

```
export GENESIS_SIGNATURE=db9246d6f102bde5857732378382dd2b1564db213256c8e81512902cde53ee244a8b22ced65234b76656b8db925c1b78db6bb91e99efe4d8ba2c2747f27b025001
```

7. Run a master node (note that if it's being run in another terminal, this terminal needs to either be aware of the environment variables set in previous steps or replace the variables in the next command with the appropriate values; this also applies to the next step).

```
cx --publisher --genesis-address $GENESIS_ADDRESS \
		    --genesis-signature $GENESIS_SIGNATURE \
		    --secret-key $SECRET_KEY \
		    --public-key $PUBLIC_KEY
```

8. Run a peer node (check previous step's note in parenthesis):

```
cx --peer --genesis-address $GENESIS_ADDRESS \
		    --port 6001 \
		    --genesis-signature $GENESIS_SIGNATURE \
		    --public-key $PUBLIC_KEY
```

9. Create a wallet (note that that seed is the one that has to be used):

```
cx --create-wallet --wallet-seed "museum nothing practice weird wheel dignity economy attend mask recipe minor dress"
```

10. Restart the peer node by stopping the process initiated in step 8, and run the command shown in step 8. This step is necessary so the peer node loads the wallet created in step 9.

11. Broadcast a transaction by running:

```
cx --secret-key $SECRET_KEY --broadcast matrix-txn.cx
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/404199/58527692-8fd2c100-8188-11e9-8446-94d2d9e3ca68.png)

**Desktop (please complete the following information):**
 - OS: Debian 9.8 x86_64
 - CX Version 0.7beta

**Comment by gz-c** [comment]
Some relevant notes:

The /wallet/transaction endpoint does automatic unspent output selection for building a transaction, unless the UTXO(s) are specified in the request.

The error message is likely erroneous in this case; there may be UTXOs available, but after collecting and filtering them into a viable transaction, there were no outputs.  So the underlying reason, most likely due to a size constraint, is obscured. But, tou will probably find the problem not far from where that error is reported, working backwards.
