### ISSUE TITLE
len(str) vs. len(struct.struct.str)

### ISSUE THREAD

**Issue by vidya88** [skycoin/cx#4]
@4rchim3d3s commented on Aug 16

**Describe the bug**

```
struct.struct.str =""

len("") returns 0
len(struct.struct.str) returns 1065353216

str.print(struct.struct.str) prints out ""
```
**To Reproduce**
make structure that has got a structure that has an strinng value
set value to ""

call len like described above.

**Expected behavior**
returns 1065353216 instead of 0

**Desktop (please complete the following information):**

- OS: win10
- CX Version 0.7.1

**Comment by vidya88** [comment]
@ingwal commented on Sep 9

Hi,
This bug report is probably clear enough that we will be able to identify the bug and fix it. But it would help us a lot - and save time - if you could create a small self-contained CX program that shows the issue.

Thanks in advance!

**Comment by vidya88** [comment]
@4rchim3d3s commented on Sep 9

Ok, so it is more complicated than i thought.
There is no bug like described. I did a short test script, but i always get 0 as length.

Somehow in one of my functions when i define a new str it automatically returns the length 1065353216.

so function looks something like this:

```
func eraseCharRight(ib Inputbox)(ib Inputbox){
var new_string str
// when i do i32.print(len(new_string)) in here i get printed "1065353216"
... more lines
}

```
I have no clue why this happens.
In a testscript i wrote i did the same but get returned a "0"

I will dig deeper into this when i have time for it.

**Comment by jdknives** [comment]
Ping

**Comment by archerixx** [comment]
Tried reproducing issues with following code:
```
package main

type a struct{
	st b
}

type b struct{
	text str
}

func main (){

	var s1 a
	s1.st.text =""

	i32.print(len("")) //returns 0
	i32.print(len(s1.st.text)) //returns 0

	str.print(s1.st.text) //prints out ""
}
```

But both len() function returned correct value, which is `0`
