### ISSUE TITLE
Fix Issue 28 Tests

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#400]
Rename tests
- uint8 test
- uint16 test, 

1> All tests for one data type (int32, int62, f32) in one file
example:
issue-28-int32.cx
issue-28-int64.cx

For type

-- Signed Ints
- int8
- int16
- int32
- int64

-- Unsigned Ints
- uint8
- uint16
- uint32
- uint64

-- Floats
- f32
- f64

2> For each test we need example of 
- positive literal (ex. x += 3)
- negative literal ( ex x += -5
-  variable ( x+= y).

3> Tests must be for the following types

And we need to test the following operators

Arithmetic Operators
- x + y
- x - y
- x * y
- x / y

-- increment/decrement operators
- x ++ (increment)
- x -- (decrement)

-- addition/subtraction assignment operators
- x += y  (addition assignment operator)
- y += y (subtraction assignment operator)

-- multiplication and division assignment operators
- x *= y (multiplication assignment operator)
- x /= y (division assignment operator)

LOGIC OPERATORS CAN BE IGNORED. CAN BE ANOTHER TICKET

-- shift and bit manipulation assignment operators
- x >>= y (right shift assignment operator)
- x <<= y (left shift assignment operator)
- x %= y (modulus assignment operator)
- x &= y (and assignment operator)
- x |= y (or assignemnt operator)
- x ^= y (xor assignment operator

-- bit manipulation operators
- x >> y
- x << y
- x % y
- x & y
- x |= y
- x ^ y

DO NOT TEST THESE. NOT IN LANGUAGE.
- -- x (pre increment). DO NOT TEST THESE. NOT IN LANGUAGE.
- -- x (pre decrement). DO NOT TEST THESE. NOT IN LANGUAGE.

3> one file for each operator, not fifteen files

<img width="360" alt="Screenshot 2021-02-28 at 10 24 05 AM" src="https://user-images.githubusercontent.com/54745307/109406069-0d0c1500-79b1-11eb-9e71-6ca4952155b7.png">

4> have one function for testing each case; then have a function in file that call the test functions

5> make sure test files are put in array in main.cx (list of tets)

**Comment by PratikDhanave** [comment]
work in progress
