### ISSUE TITLE
Build issues after go get on Ubuntu 20.04

### ISSUE THREAD

**Issue by AdeilH** [skycoin/cx#418]
OS: Ubuntu Budgie 20.04

Issue: I can run make build and make install if I clone the repo but not when I use 

`go get github.com/skycoin/cx`
![Screenshot from 2021-03-01 16-42-26](https://user-images.githubusercontent.com/10462189/109492797-50e44480-7aad-11eb-935c-dc2403284c17.png)

Also when I use go get I get the files in GOPATH/pkg/mod/github.com.... and not as mentioned in README.md

Attaching the screenshot for working make tests when repo is cloned directly from git. 
![Screenshot from 2021-03-01 16-46-17](https://user-images.githubusercontent.com/10462189/109493022-b3d5db80-7aad-11eb-8f08-f4181c6faaf3.png)

**Comment by SkycoinSynth** [comment]
Can you post the other images?

**Comment by AdeilH** [comment]
Attaching screenshots of issues when building program via go get. issue with make clean and issue while building cx-games. 

![Screenshot from 2021-03-01 16-36-29](https://user-images.githubusercontent.com/10462189/109508946-38325980-7ac2-11eb-8ae8-e8258c1e0819.png)

![Screenshot from 2021-03-01 12-22-14](https://user-images.githubusercontent.com/10462189/109509050-513b0a80-7ac2-11eb-9de2-6b5a48ab47a1.png)


![Screenshot from 2021-03-01 11-46-29](https://user-images.githubusercontent.com/10462189/109509155-6b74e880-7ac2-11eb-95a9-29301fc67507.png)
