### ISSUE TITLE
Error message is irritating

### ISSUE THREAD

**Issue by Lunier** [skycoin/cx#42]
When a method has 4 parameter for example and you call the method with only 3, you get the following error message:
`panic: runtime error: index out of range`

It's kind of irritating since you would search for an array access error or sth. like that.

Would it be possible to get a better error message?

**Comment by amherag** [comment]
Yeah, we only have some basic error reporting for now. The panics come from Golang, not CX. In general, CX will try to catch errors, and if it fails to do so, Golang will then panic.

Sorry about it. I hope I can fix several issues this week, including yours.

**Comment by amherag** [comment]
Solved! Now if you try to send, for example, 2 input arguments to a function that expects 3, it will throw an error. Exceptions to this are functions which expect any number of input arguments, such as printf and sprintf.
