### ISSUE TITLE
Escape code errors

### ISSUE THREAD

**Issue by vidya88** [skycoin/cx#44]
@ReewassSquared commented on Jun 9

This is expanding on issue [#306](https://github.com/skycoin/cx/issues/306).

escape codes for single and double quotes do not function as intended. Single quotes throws an error "unexpected single quote".

Not sure why the error would be happening for single quotes as well.

**Comment by vidya88** [comment]
@ingwal commented on Jun 14

Hi, and thanks for the report.
Do you have an example code snippet that shows the problem? That would help a lot towards fixing it.

**Comment by vidya88** [comment]
@ReewassSquared commented on Jun 14

yeah I'll send examples in a tad

**Comment by SkycoinSynth** [comment]
Closed. No example. Cant replicate.
