### ISSUE TITLE
Example issue `datatypes-declarations.cx`

### ISSUE THREAD

**Issue by archerixx** [skycoin/cx#440]
Running [`datatypes-declarations.cx`](https://github.com/skycoin/cx/blob/develop/examples/book/datatypes-declarations.cx) from cx/examples/book produces error:
```
error: datatypes-declarations.cx:4 struct 'byte' not found in package 'main'
```

**Comment by SkycoinSynth** [comment]
Byte was replaced with u8 or i8?

**Comment by archerixx** [comment]
It seems it is `i8` which works. `u8` is not in `main` package either
