### ISSUE TITLE
New CX playground

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#445]
1> There is an executable in /cmd/cxplayground,
- it launches a web-server

2> We want this web-server to serve a one page website
- there are two text input boxes on a single page
- code goes into the top box
- the user hits a button and the content of the top box are sent to the server
- the output from the server appears in the bottom box

3> The website has a box at the top, that a user enters code
4> The user hits a button, and the code is sent to the server, compiled and execute
5> The output from the server is displayed in the bottom box

---

In cx/cmd/cxplayground
- create a folder called, "template" and put the HTML template in there, if you are unable to embed the HTML template in the golang file

---

- create a folder called "examples" in cx/cmd/cxplayground. We will put files likes "example1.cx", "example2.cx", etc in this folder
-
When the cxplayground web-app starts, it should scan the ./examples/ folder and record the names of each of the files in the folder and also the text contained in the folder.
- a list of files names (slice)
- a map, mapping from the file name, to the contents in the file

- Make a left hand column list, with one entry for each text file in the /examples folder (or can use a dropdown)
- If the user clicks the example from the list or selects it from the dropbox, then copy the text from the example into the top input box

---

To test current API

do "go run main.go" in the cxplayground folder to launch the web-server

Then run

```
 curl -H "Content-Type: application/json" -X POST -d '{"code": "package main; func main() {str.print(\"Hello, world!\");}"}' http://localhost:5336/eval
```

This feeds a test input in and then gets the output back from the server.

---

That is it.

The part where the server receives the code and executes it is already done.

We just need the HTML template, and the dropdown. And to populate the template.

**Comment by amherag** [comment]
PR #446 addresses point 1 mentioned in the description of this issue.
