### ISSUE TITLE
CX does not compile without "-tags full"

### ISSUE THREAD

**Issue by gz-c** [skycoin/cx#448]
This command fails:

```sh
$ go build -i -o /Users/gz-c/.gopath/bin/cx github.com/skycoin/cx/cxgo/
```

```
go build -i -o /Users/gz-c/.gopath/bin/cx github.com/skycoin/cx/cxgo/
# github.com/skycoin/cx/cxgo/actions
cxgo/actions/postfix.go:275:19: undefined: ConstCodes
cxgo/actions/postfix.go:276:17: undefined: Constants
```

CX does not compile without "-tags full".

I tried compiling with `-tags full` to compile without the OpenGL dependency, but this failed.

**Comment by 0pcom** [comment]
building CX without OpenGL:

`go build -tags base -i -o $GOPATH/bin/cx github.com/skycoin/cx/cxgo/`
