### ISSUE TITLE
Unable to get version 0.7.5

### ISSUE THREAD

**Issue by Diablo2050** [skycoin/cx#486]
current version is 0.7.1, tried building it again from repo with default develop branch but still got  0.7.1

OS:
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

kernel 5.4.0-66-generic

- I ran git clone
- make build
`mod=vendor go build -tags="base cxfx" -o ./bin/cx github.com/skycoin/cx/cmd/cx
go: inconsistent vendoring in /home/amr/Documents/misc/golang/cx:
	golang.org/x/mod@v0.4.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/sys@v0.0.0-20210305230114-8fe3ee5dd75b: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/tools@v0.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	modernc.org/goyacc@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	modernc.org/mathutil@v1.2.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	modernc.org/sortutil@v1.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	modernc.org/strutil@v1.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	modernc.org/y@v1.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
make: [Makefile:68: build] Error 1 (ignored)
chmod +x ./bin/cx
chmod: cannot access './bin/cx': No such file or directory
make: *** [Makefile:69: build] Error 1`

- ran go mod vendor
`go: downloading github.com/skycoin/skycoin v0.27.1
go: downloading github.com/jinzhu/copier v0.2.4
go: downloading github.com/sirupsen/logrus v1.8.0
go: downloading github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7
go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20201108214237-06ea97f0c265
go: downloading github.com/mjibson/go-dsp v0.0.0-20180508042940-11479a337f12
go: downloading github.com/skycoin/gltext v0.0.0-20200425002731-afdd8ff94e14
go: downloading golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56
go: downloading github.com/satori/go.uuid v1.2.0
go: downloading github.com/magefile/mage v1.10.0
go: downloading github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0
go: downloading golang.org/x/image v0.0.0-20190802002840-cff245a6509b`

- make build
mod=vendor go build -tags="base cxfx" -o ./bin/cx github.com/skycoin/cx/cmd/cx
chmod +x ./bin/cx

- make install 
mkdir -p /home/amr/cx/src /home/amr/cx/bin /home/amr/cx/pkg
NOTE:	CX workspace at /home/amr/cx
NOTE:\tWe recommend you to test your CX installation by running "cx ./tests"
./bin/cx -v
CX version 0.7.1 linux/amd64

- make test
# go test -mod=vendor -race -tags base github.com/skycoin/cx/cxgo/
./bin/cx ./lib/args.cx ./tests/main.cx ++wdir=./tests ++disable-tests=gui,issue ++cxpath=/home/amr/Documents/misc/golang/cx/bin/cx

Running CX tests in dir : './tests'
Enabled tests : 1 : [ stable,  ]
Enabled log : 4 : [ fail,  ]

A total of 156 tests were performed
156 were successful
0 failed
32 skipped

**Comment by Diablo2050** [comment]
running cx version i get:
`CX version 0.7.1 linux/amd64`

**Comment by SkycoinSynth** [comment]
Fixed.
