### ISSUE TITLE
No compilation error when assigning an literal which overflow the receiving type

### ISSUE THREAD

**Issue by vidya88** [skycoin/cx#49]
@asahi3g commented on May 10

**Describe the bug**
No compilation error when assigning an literal which overflow the receiving type

**To Reproduce**
```
package main
func main ()() {
	var b0 byte = 256B
	var b1 byte = -1B
	test(false, true, "must not compile")
}
```
**Expected behavior**
Compilation error like golang.
eg : "constant -1 overflows byte"

**Screenshots**

```
byts1 [0]
byts2 [1]
pending_0.cx: 6: result was not equal to the expected value; must not compile
```
**Desktop (please complete the following information):**

- OS: linux
- CX Version 0.6.2 commit 4ba0d2d

**Comment by vidya88** [comment]
@ingwal commented on May 31

Byte is actually signed, so you shouldn't get an error on the -1. 256B is still wrong, though.

**Comment by vidya88** [comment]
@asahi3g commented on May 31

Is byte supposed to follow golang's behaviour (it's uint8 in go https://golang.org/pkg/builtin/#byte) ?

Here's a discussion about removing byte from go: golang/go#22180

**Comment by archerixx** [comment]
This code now produces error: (`byte` is replaced by `i8`)
```
package main

func main ()() {
	var b0 i8 = 256B
	var b1 i8 = -1B
}
```

Error:
```
[4:20] invalid unsigned byte literal: 256
[4:20] invalid unsigned byte literal: 256
```

This ticket can be closed

**Comment by SkycoinSynth** [comment]
Closed. Fixed.
