### ISSUE TITLE
slow cx execution times

### ISSUE THREAD

**Issue by steadyclackin** [skycoin/cx#5]
On Xubuntu 16.04 with a clean cx install (via method 1), running the cx examples locally is quite CPU intensive. Running any one of them pegs a core for several seconds (my system is 3Ghz and has 4 cores). This seems too slow for integration with other tech in the sky ecosystem, e.g. the blockchain (via "smart contracts" or "consensus programs" or whatever it'll be called). What's the integration roadmap and what runtime speed is required for the integration?

**Comment by amherag** [comment]
CX is indeed very slow at the moment. BUT! we've done something already :) A new runtime prototype is ready now, and it's far faster than the implementation you installed.

The implementation that you installed ran about 4x-20x (depending on the benchmark) slower than Python 3. Now, doing some benchmarks, CX is running around 1.2x slower than Python 3, and there are still many optimizations to implement.

Hopefully this new version should replace the main one in the following weeks.

**Comment by steady-clackin** [comment]
Great! This stuff you mention is in the dev branch? Is it stable enough for me to try out?

**Comment by amherag** [comment]
The "fast" CX is now the master branch. Sorry for the delay and for not answering before!

**Comment by olemis** [comment]
@amherag slow is relative . Why not better have a profiler, performing performances and a way for them to generate reports out of the data generated by all these ? (<= which itself deserves a separate issue).
