### ISSUE TITLE
No compilation error when global variable is redeclared at local scope.

### ISSUE THREAD

**Issue by vidya88** [skycoin/cx#51]
@asahi3g commented on May 10

**Describe the bug**
Variable declared at global scope can be redeclared at local scope without compilation error.

**To Reproduce**

```
package main
var i i32 = 55
func main()() {
	var i i32 = 44
	panic(true, false, "must not compile")
}
```
**Expected behavior**
Compilation error stating i is redeclared

**Desktop (please complete the following information):**

- OS: linux
- CX Version 0.6.2 commit 4ba0d2d

**Additional context**

**Comment by archerixx** [comment]
Golang supports this. You can redeclare variable at local scope without compile error.
Following code in golang works:
```
package main
import "fmt"

var i int = 55

func main() {
	var i int = 44
	fmt.Println(i)
}
```

**Comment by SkycoinSynth** [comment]
Should be warning. Is not error.
