### ISSUE TITLE
Comment out unused variables and functions in goyacc.

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#563]
cmd/goyacc/golex/lex/all_test.go:16:6: func caller is unused (U1000)
cmd/goyacc/golex/lex/all_test.go:26:6: func dbg is unused (U1000)
cmd/goyacc/golex/lex/all_test.go:41:6: func use is unused (U1000)
cmd/goyacc/golex/lex/example_test.go:144:2: this value of c is never used (SA4006)
cmd/goyacc/golex/main.go:31:6: type renderer is unused (U1000)
cmd/goyacc/golex/main.go:35:6: type writer is unused (U1000)
cmd/goyacc/golex/render.go:241:8: printf-style function with dynamic format string and no further arguments should use print-style function instead (SA1006)
cmd/goyacc/lex/all_test.go:24:6: func caller is unused (U1000)
cmd/goyacc/lex/all_test.go:34:6: func dbg is unused (U1000)
cmd/goyacc/lex/all_test.go:49:6: func use is unused (U1000)
cmd/goyacc/lex/parser.go:12:8: package "fmt" is being imported more than once (ST1019)
	cmd/goyacc/lex/parser.go:16:2: other import of "fmt"
cmd/goyacc/lex/parser.go:102:7: const yyNprod is unused (U1000)
cmd/goyacc/lex/parser.go:105:5: var yyTokenNames is unused (U1000)
cmd/goyacc/lex/parser.go:106:5: var yyStates is unused (U1000)
cmd/goyacc/lex/parser.go:530:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:542:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:548:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:560:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:591:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:604:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:617:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:674:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:691:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:713:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:719:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:734:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:778:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:784:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/parser.go:796:3: this value of yyDollar is never used (SA4006)
cmd/goyacc/lex/ranges.go:56:23: func (*rangeSlice).invert is unused (U1000)
cmd/goyacc/lex/rule.go:96:2: redundant return statement (S1023)
cmd/goyacc/lex/scanner.go:31:2: field val is unused (U1000)
cmd/goyacc/lex/stateset.go:43:20: func (*stateSet).clear is unused (U1000)
cmd/goyacc/lexer/regex.go:218:6: should use !strings.ContainsAny(string(arune), more) instead (S1003)
cmd/goyacc/parser/nquads/all_test.go:16:6: func caller is unused (U1000)
cmd/goyacc/parser/nquads/all_test.go:26:6: func dbg is unused (U1000)
cmd/goyacc/parser/nquads/all_test.go:41:6: func use is unused (U1000)
cmd/goyacc/parser/nquads/all_test.go:43:6: func hd is unused (U1000)
cmd/goyacc/parser/nquads/all_test.go:952:3: string literal contains Unicode control characters, consider using escape sequences instead (ST1018)
cmd/goyacc/parser/nquads/all_test.go:962:3: string literal contains the Unicode control character U+0080, consider using the '\u0080' escape sequence instead (ST1018)
cmd/goyacc/parser/nquads/parser.go:36:7: const illegal is unused (U1000)
cmd/goyacc/parser/nquads/parser.go:64:7: const yyNprod is unused (U1000)
cmd/goyacc/parser/nquads/parser.go:67:5: var yyTokenNames is unused (U1000)
cmd/goyacc/parser/nquads/parser.go:68:5: var yyStates is unused (U1000)
cmd/goyacc/parser/yacc/all_test.go:20:6: func caller is unused (U1000)
cmd/goyacc/parser/yacc/all_test.go:30:6: func dbg is unused (U1000)
cmd/goyacc/parser/yacc/all_test.go:45:6: func use is unused (U1000)
cmd/goyacc/parser/yacc/goscanner.go:107:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/goscanner.go:126:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/goscanner.go:141:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/goscanner.go:160:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/goscanner.go:212:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/goscanner.go:240:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/goscanner.go:246:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/goscanner.go:307:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/goscanner.go:366:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/parser.go:490:5: this value of ok is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:16:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:92:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:111:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:155:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:269:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:302:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:371:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:460:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:502:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:544:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:588:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:612:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:654:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:660:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:666:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:685:2: this value of c is never used (SA4006)
cmd/goyacc/parser/yacc/scanner.go:735:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/nquads/all_test.go:17:6: func caller is unused (U1000)
cmd/goyacc/scanner/nquads/all_test.go:27:6: func dbg is unused (U1000)
cmd/goyacc/scanner/nquads/all_test.go:42:6: func use is unused (U1000)
cmd/goyacc/scanner/nquads/all_test.go:44:6: func hd is unused (U1000)
cmd/goyacc/scanner/nquads/all_test.go:132:5: ineffective break statement. Did you mean to break out of the outer loop? (SA4011)
cmd/goyacc/scanner/nquads/all_test.go:180:4: string literal contains Unicode control characters, consider using escape sequences instead (ST1018)
cmd/goyacc/scanner/nquads/etc.go:79:2: field sc is unused (U1000)
cmd/goyacc/scanner/nquads/etc.go:99:19: func (*Scanner).back is unused (U1000)
cmd/goyacc/scanner/nquads/scanner.go:98:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/nquads/scanner.go:196:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/nquads/scanner.go:213:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/nquads/scanner.go:349:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/nquads/scanner.go:362:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/all_test.go:17:6: func dbg is unused (U1000)
cmd/goyacc/scanner/yacc/scanner.go:433:2: this value of c0 is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:492:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:538:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:650:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:681:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:748:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:833:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:873:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:913:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:955:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:977:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1017:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1021:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1025:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1053:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1057:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1083:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1122:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1204:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1338:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1357:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1412:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1443:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1460:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1464:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1477:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1481:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1485:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1498:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1513:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1517:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1521:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1536:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1540:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1564:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1612:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1629:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1684:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1712:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1716:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1733:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1746:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1750:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1763:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1778:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1791:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1804:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1808:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:1821:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:3031:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:3046:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:3050:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:3054:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:3067:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:3117:2: this value of c is never used (SA4006)
cmd/goyacc/scanner/yacc/scanner.go:3154:2: this value of c is never used (SA4006)
cmd/goyacc/y/all_test.go:32:6: func caller is unused (U1000)
cmd/goyacc/y/all_test.go:42:6: func dbg is unused (U1000)
cmd/goyacc/y/all_test.go:57:6: func use is unused (U1000)
cmd/goyacc/y/all_test.go:71:18: func itemSet.dump is unused (U1000)
cmd/goyacc/y/all_test.go:80:19: func itemSet1.dump is unused (U1000)
cmd/goyacc/y/all_test.go:477:4: this value of l is never used (SA4006)
cmd/goyacc/y/api.go:607:2: field sym is unused (U1000)
cmd/goyacc/y/api.go:625:17: func (*State).zpath is unused (U1000)
cmd/goyacc/y/y.go:38:2: var isTesting is unused (U1000)
cmd/goyacc/y/y.go:145:16: func item1.dump is unused (U1000)
cmd/goyacc/y/y.go:239:6: type itemSet1 is unused (U1000)
cmd/goyacc/y/y.go:241:19: func itemSet1.add is unused (U1000)

**Comment by hunzlahmalik** [comment]
Working on it
