### ISSUE TITLE
cx/serialize.go: Change "dsFunction" and other names to "DeserializeFunction"

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx#577]
cx/serialize.go: Change "dsFunction" and other names to "DeserializeFunction"

**Comment by hunzlahmalik** [comment]
Can you please explain what do you mean by other names. There is 'dsName' 'dsBool' etc. Should I change all of them?

**Comment by kenje4090** [comment]
I have already done this, will make PR in a while
