### ISSUE TITLE
pointer to structure array indexed object

### ISSUE THREAD

**Issue by vidya88** [skycoin/cx#6]
@4rchim3d3s commented on Aug 13

**Describe the bug**

Trying to pass a pointer to an address of a structure within an array

```
error: cx-template\inputs\inputHandler.cx:222 invalid indexing
error: cx-template\inputs\inputHandler.cx:222 function 'updateSliderPosition' expected input argument of type '*Slider'; '*[20]Slider' was provided
```
**To Reproduce**

1. git clone https://github.com/4rchim3d3s/cx-template
2. change screenHandler.cx line 422-425 into

```
func updateSliderPosition(slider *sliderHandler.Slider, mouse_x f64)(){
	*slider.slider_x = absolute2relativeX(f64.i32(mouse_x), current_screen.width)
	*slider = sliderHandler.limitPosition(slider)
	*slider = sliderHandler.setValueByPosition(slider)
}
```
3. change inputHandler.cx line 222 to

`screenHandler.updateSliderPosition(&screen.sliders[i], mouse_x)`

**Desktop (please complete the following information):**

- OS: WIN10
- CX Version 0.7.1

**Comment by vidya88** [comment]
@ingwal commented on Sep 9

4rchim3d3s commented on Aug 13

**Comment by vidya88** [comment]
@ingwal commented on Sep 9

Setting the milestone to 0.7.2 because it looks like an array problem. If it turns out not to be, then we can move it to later.

**Comment by archerixx** [comment]
I tried reproducing this issue and I get can produce this error:
```
error: screenHandler.cx:423 invalid indirection
error: screenHandler.cx:424 function 'limitPosition' expected input argument of type 'Slider'; '*Slider' was provided
error: screenHandler.cx:425 function 'setValueByPosition' expected input argument of type 'Slider'; '*Slider' was provided
```

After fixing indirection in `updateSliderPosition` func it looks like this and runs without errors:
```
func updateSliderPosition(slider *sliderHandler.Slider, mouse_x f64)(){
	slider.slider_x = absolute2relativeX(f64.i32(mouse_x), current_screen.width)
	*slider = sliderHandler.limitPosition(*slider)
	*slider = sliderHandler.setValueByPosition(*slider)
}
```
