### ISSUE TITLE
Return from a function doesnt work

### ISSUE THREAD

**Issue by Lunier** [skycoin/cx#65]
![image](https://user-images.githubusercontent.com/22796843/45931860-4d5f4180-bf74-11e8-8a33-c4e57a6ad62e.png)

The function checkNeighbours returns a number, in this case you see "mine" printed to the console so it returned -1, but the printf statements prints a 0 which is false.

Code:
[https://github.com/Lunier/Minesweeper]()

**Comment by corpusc** [comment]
since this was opened, returns have been enabled.  
but not with arguments.
