### ISSUE TITLE
Unify op source code

### ISSUE THREAD

**Issue by vidya88** [skycoin/cx#74]
@olemis commented on Jan 2

**Describe the bug**

There is duplicated code implementing op codes behavior e.g. cx/op_i32.go is exactly the same as cx/op_i64.go except for (see grep -v ) :

- 32 => 64
- comments

so, different op codes led to duplicated code in the source code base which is hard to maintain (changes doing the same at multiple locations)

**To Reproduce**

In my working copy (and develop)
```
$ diff -u cx/op_i32.go cx/op_i64.go | grep '^[-+]' | grep -v 32 | grep -v 64 | grep -v '[-+]//'
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
```
**Expected behavior**
Write a single implementation for arithmetic opcodes

**Desktop (please complete the following information):**

- OS: all
- CX Version: CX version 0.5.18

**Comment by vidya88** [comment]
@ingwal commented on Jan 2

1. I don't think this issue has high priority right now because we already have working code, and we need to prioritize to get 0.6 out ASAP.
2. I think that if we have a fixed set of basic data types (i8/byte, i32, i64, f32, f64, string), maintaining a set of basic opcodes for basic numeric operations, the relatively small code for that will not be difficult to maintain. This is especially true if we make sure to have a good test suite for those basic types, something that is not really the case right now. However, it should be reasonably easy to do.
3. Execution speed will be much higher the simpler each opcode is to execute. This is not the case when each opcode has to decide which datatype it is currently operating on. That information is already present when parsing the program so in fact I think that the general (non type specific) operators should be removed.

**Comment by vidya88** [comment]
@olemis commented on Jan 3

I'm completely in favor of arguments 1 and 3 above , nonetheless I do not think that the second is convincing enough . Right now [#198](https://github.com/skycoin/cx/pull/198) required a single modification that involved changing 5 files to do exactly the same thing in 5 different places . That's wrong and it is what shall be solved so as to close this issue .

**Comment by SkycoinSynth** [comment]
Retarded. No change.

**Comment by SkycoinSynth** [comment]
Since each assembly operation is on a different data type and the operations are atomic, there has to be duplication.

You should be able to import f32 type only and not f64 or f64 and not f32, depending on CPU and system. Some embedded systems only have int32 and do not have floating point processors and therefore floating point is non-atomic on these systems.

Atomic operations should not need modification too often.
