### ISSUE TITLE
can't prefix a (f32) variable with minus to flip it's signedness

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#75]
it gives no error, but doesn't work.

however, you CAN prefix a literal (f32 number) this way, and that DOES work.

**Comment by ingwal** [comment]
That is because the minus character is part of the number, i.e. handled by the lexer.  This needs to be moved to the parser instead so that it will work for both cases.

**Comment by olemis** [comment]
I think this will be fixed as part of the patch for #141

**Comment by olemis** [comment]
Maybe related to the fact that there is no case for `-` in `UnaryExpression` switch .
