### ISSUE TITLE
i32 and i64 operators have ridiculous implementations

### ISSUE THREAD

**Issue by vidya88** [skycoin/cx#77]
@ingwal commented on Dec 29, 2018

**Describe the bug**
Many of the operators in cx/op_i32.go and cx/op_i64.go either don't make sense or have ridiculous implementations. I give you the following example:

func opI32Max(expr *CXExpression, fp int) {
inp1, inp2, out1 := expr.Inputs[0], expr.Inputs[1], expr.Outputs[0]
outB1 := FromI32(int32(math.Max(float64(ReadI32(fp, inp1)), float64(ReadI32(fp, inp2)))))
WriteMemory(GetFinalOffset(fp, out1), outB1?)
}

Why should we go via conversion to float64 and then use math.Max()?

Another issue is that some of the functions don't make sense, for instance i32.log() and other similar functions that should only be defined on floating point values.

These files should be cleaned up, and I suspect that we will gain some speed in the process.

**To Reproduce**

1. look in e.g. cx/op_i32.go
2. gasp in horror
**Expected behavior**
The implementation should be the simplest possible, which I suspect is also the fastest possible.

Another idea to make it even faster without losing clarity is to skip the call altogether and instead make the functions inline in opcodes_bare.go where they are called.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- CX Version: 0.5.18

**Additional context**
N/A

**Comment by rizary** [comment]
@SkycoinSynth you can close this issue since this has been fixed.
