### ISSUE TITLE
Automate cx.skycoin.net deployment

### ISSUE THREAD

**Issue by vidya88** [skycoin/cx#80]
@amherag commented on Dec 10, 2018

@gz-c commented to me that the site deployment can be automated. The more important things to automate are: 1) show what CX version is being run for the playground (so users can create issues related to specific versions of CX), and 2) update the CX being run by the playground.

If it helps, you can get the CX version can be obtained by running cx -v.

**Comment by vidya88** [comment]
@olemis commented on Dec 11, 2018

@amherag github pages ?

**Comment by vidya88** [comment]
@gz-c commented on Dec 11, 2018

@iketheadore @therealssj

**Comment by vidya88** [comment]
@iketheadore commented on Dec 24, 2018

Where's the code of cx.skycoin.net?

**Comment by vidya88** [comment]
@therealssj commented on Dec 30, 2018 

@iketheadore https://github.com/skycoin/cx-website

**Comment by iketheadore** [comment]
Deployed on cx.skycoin.com and skycoin.com/cx. The playground has been removed for security.
