### ISSUE TITLE
CX.bat (for Windows users)

### ISSUE THREAD

**Issue by WCMotoNaka** [skycoin/cx#80]
Links get a 404 error
I think there has been an update can we get the link repaired?

**Comment by corpusc** [comment]
he's talking about a "Batch script" link on this page:    https://github.com/skycoin/cx/blob/master/README.md#cx-programming-language


under CX Installation | Windows section.
somebody please update the website link,
as the file is now named cx-setup.bat

**Comment by BigOokie** [comment]
About to raise a PR to resolve this
