### ISSUE TITLE
Method does not work

### ISSUE THREAD

**Issue by ingwal** [skycoin/cx#85]
In the small program below, the method 'init' does not work.  It does nothing to the Card struct that it is supposed to operate on.

package main

// Constants
var Clubs    i32 = 0
var Diamonds i32 = 1
var Spades   i32 = 2
var Hearts   i32 = 3

type Card struct {
    suit i32
    rank i32
}

func (c Card) init(suit i32, rank i32) {
     c.suit = suit
     c.rank = rank
}

func (c Card) print() {
    printf("[%d %d]\n", c.suit, c.rank)
}

func main() {
    var card  Card

    // Initialized to [0, 0]
    card.print()

    // Bug: This does not work.
    card.init(Diamonds, 4)
    card.print()

    // This does work
    card.suit = Diamonds
    card.rank = 4
    card.print()
}

**Comment by amherag** [comment]
You'd need to declare your method with a pointer receiver. If you run a similar program in Golang, the struct will not be modified either (check code below).

So the solution is to declare your `init` method with this signature: `func (c *Card) init(suit i32, rank i32)`, which doesn't work :) just for reference that the code you posted works as intended. I'll now open a new issue about pointer receivers not working.

```
package main

import "fmt"

type Card struct {
	suit int
	rank int
}

func (c Card) init (suit int, rank int)  {
	c.suit = suit
	c.rank = rank
}

func (c Card) print () {
	fmt.Printf("[%d %d]\n", c.suit, c.rank)
}

func main () {
	var card Card
	card.print()
	card.init(1, 4)
	card.print()
}
```
