### ISSUE TITLE
affordance tutorial syntax errors

### ISSUE THREAD

**Issue by vidya88** [skycoin/cx#90]
@steadyclackin commented on Jan 24, 2018

On Xubuntu 16.04 with a clean cx install (via method 1), running the first 3 affordances tutorial files produces syntax errors. The 4th tutorial file runs without any syntax errors.
```
$ cx ./go/src/github.com/skycoin/cx/examples/affordances/tutorial-01.cx 
23: syntax error: unexpected MULT
23: syntax error: unexpected MULT
$ cx ./go/src/github.com/skycoin/cx/examples/affordances/tutorial-02.cx 
34: syntax error: unexpected MULT
34: syntax error: unexpected MULT
$ cx ./go/src/github.com/skycoin/cx/examples/affordances/tutorial-03.cx 
52: syntax error: unexpected MULT
52: syntax error: unexpected MULT
```

**Comment by vidya88** [comment]
@amherag commented on Jan 25, 2018

I should have read all the issues you crated first. Yeah I need to update them. Sorry, whenever I touch stuff related to affordances, it's usually a big update and things break.

**Comment by vidya88** [comment]
@ingwal commented on Dec 31, 2018

This is part of the task of getting all examples in the book to work.

**Comment by SkycoinSynth** [comment]
Affordances are being refactored. We have to update book later, because we changed to many things.

New book version will be for CX 1.0
