### ISSUE TITLE
Variable redeclaration should not be allowed

### ISSUE THREAD

**Issue by amherag** [skycoin/cx#98]
The parser should complain about this:

```
package main

func main () {
	var foo i32
	var foo i32
	var foo i32
	foo := 5

	i32.print(foo)
}
```

`foo := 5` is a synonymous of `var foo i32` so the parser not complaining about that short variable declaration is related.

**Comment by ingwal** [comment]
Hmm, I thought that redeclarations were allowed.  Is that only under certain circumstances?

**Comment by corpusc** [comment]
example code was added to the project (find the "book" folder) which demonstrates FUNCS being redeclared.

**Comment by amherag** [comment]
Yeah, function redeclaration is allowed, not variables.
